name: Jelly Bot - Test on push

on: [push]

jobs:
  print-info:
    runs-on: windows-latest

    steps:
      - name: Print SHA
        shell: cmd
        run: |
          echo %GITHUB_SHA%

      - name: Print REF
        shell: cmd
        run: |
          echo %GITHUB_REF%

  style-check:
    runs-on: windows-latest

    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          pip install flake8

      - name: Perform syntax check
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Perform style check
        run: |
          flake8 . --count --exit-zero --max-complexity=15 --max-line-length=120 --ignore=F401,F403,F405 --statistics

  test:
    runs-on: windows-latest

    timeout-minutes: 10

    env:
      SECRET_KEY: ${{ secrets.DjangoSecretKey }}
      DJANGO_SETTINGS_MODULE: JellyBot.settings
      MONGO_URL: ${{ secrets.MongoDBURL }}
      MONGO_DB: GitHubActionTest
      LINE_SECRET: ${{ secrets.LINESecret }}
      LINE_TOKEN: ${{ secrets.LINEToken }}
      DISCORD_TOKEN: ${{ secrets.DiscordToken }}
      PRODUCTION: 0
      DEBUG: 1
      TEST: 1
      LOGGER: DISCORD_INTERNAL|40,MODEL_CHECK|30,PING_SPAM|10
      NO_FIELD_CHECK: 1
      GI_CLIENT_ID: ${{ secrets.GoogleIdentityClientID }}
      EMAIL_ACCOUNT: ${{ secrets.EmailAccount }}
      EMAIL_PASSWORD: ${{ secrets.EmailPassword }}
      SERVICE_SHORT_URL: http://rnnx.cc
      DDNS_PASSWORD: ${{ secrets.DDNSPassword }}
      IMGUR_CLIENT_ID: ${{ secrets.ImgurClientID }}
      DDNS_HOST: bot
      DDNS_DOMAIN: raenonx.cc

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test tests